/**
 * World Prompt Builder Service
 * Living World feature: Generates prompts for AI image generation
 *
 * This service builds prompts for:
 * 1. Base world generation - Initial barren landscape
 * 2. Evolution prompts - Adding elements as topics are learned
 *
 * The world evolves by adding a single, topic-specific element per evolution.
 * Topic-to-visual translation is handled by Gemini (not hardcoded mappings).
 */

/**
 * World style constants for consistent visual identity
 * These ensure all generated images maintain the same aesthetic
 */
export const WORLD_STYLE = {
  base: 'Painterly digital illustration inspired by Studio Ghibli, with soft edges and dreamlike quality',
  lighting: 'Consistent golden-hour lighting from upper left, casting long gentle shadows',
  palette: 'Soft watercolor textures, warm but muted colors with subtle gradients',
  atmosphere: 'Gentle mist in valleys, atmospheric perspective for depth',
  composition: '16:9 widescreen format with clear horizon line at one-third height'
}

/**
 * Build the base world generation prompt
 * Returns a prompt to generate the initial barren landscape
 *
 * @returns {string} Complete prompt for base world image generation
 */
export function buildBaseWorldPrompt() {
  return `Create a ${WORLD_STYLE.base}.

COMPOSITION (16:9 widescreen):
- SKY: Soft gradient from dawn colors at the horizon to deeper blue above, wispy clouds catching early light
- BACKGROUND: Distant mountains silhouetted against the sky, misty and ethereal
- MIDGROUND: Rolling plains and gentle terrain with sparse hardy grasses and a few low shrubs, hints of potential
- FOREGROUND: Textured earth and rock formations with a shallow streambed and a few small reflective puddles catching dawn light

MOOD & ATMOSPHERE:
- Quiet but beautiful - a world waiting to bloom
- Misty morning atmosphere, the dawn of a new world
- Sense of quiet potential and peaceful emptiness
- ${WORLD_STYLE.atmosphere}

STYLE:
- ${WORLD_STYLE.lighting}
- ${WORLD_STYLE.palette}
- Dreamlike quality with soft focus on distant elements

RESTRICTIONS:
- No text or UI elements
- No obvious buildings, large machines, or dense cities
- No lush vegetation or dense forests (keep greenery sparse and subtle in the base world)
- No characters or creatures
- Keep the landscape simple and uncluttered, like a pristine canvas

This is the beginning - a pristine canvas where knowledge will bring life.`
}

/**
 * Build an evolution prompt for adding new elements to the world
 *
 * @param {Object} options - Evolution options
 * @param {string} options.topicName - The topic just learned
 * @param {string} options.elementToAdd - Specific element to add (generated by Gemini)
 * @param {string} [options.placementHint] - Short placement hint within the frame
 * @param {'sky' | 'background' | 'midground' | 'foreground'} [options.targetLayer] - Suggested layer for placement
 * @param {string[]} [options.existingElements=[]] - What already exists in the world
 * @param {string} [options.styleDescriptor] - The world's style DNA
 * @param {string} [options.tier] - Current tier (helps scale the change)
 * @returns {string} Complete prompt for evolution image generation
 */
export function buildEvolutionPrompt(options) {
  const {
    topicName,
    summary = '',
    elementToAdd,
    placementHint = null,
    targetLayer = null,
    existingElements = [],
    styleDescriptor = WORLD_STYLE.base,
    tier = 'barren',
  } = options

  const safeTopicName = typeof topicName === 'string' ? topicName.trim() : ''
  const safeSummary = typeof summary === 'string' ? summary.trim() : ''
  const safeElementToAdd = typeof elementToAdd === 'string' ? elementToAdd.trim() : ''
  const safeExistingElements = Array.isArray(existingElements)
    ? existingElements.filter(Boolean).slice(-12)
    : []

  const layer = typeof targetLayer === 'string' ? targetLayer.trim().toLowerCase() : ''
  const layerLabel = layer ? layer.toUpperCase() : null

  if (!safeTopicName) {
    throw new Error('buildEvolutionPrompt requires topicName')
  }
  if (!safeElementToAdd) {
    throw new Error('buildEvolutionPrompt requires elementToAdd')
  }

  const placementGuidance = layer
    ? `
TARGET LAYER: ${layerLabel}
- SKY: upper third of the image (clouds, light, celestial, atmosphere)
- BACKGROUND: near the horizon (distant mountains, mesas, far features)
- MIDGROUND: center band (main landforms, structures, forests)
- FOREGROUND: lower third (water edges, paths, close terrain details)`
    : ''

  const placementHintSection = (typeof placementHint === 'string' && placementHint.trim())
    ? `\nPLACEMENT HINT: ${placementHint.trim()}`
    : ''

  const skyRestrictions = (layer === 'sky')
    ? ''
    : `
IMPORTANT RESTRICTION:
- Do NOT introduce new auroras, swirling magical sky ribbons, or dramatic new cloud formations unless the topic is explicitly about the sky/space.
- Keep the sky largely unchanged; focus the evolution in the ${layerLabel || 'ground layers'}.
- The new element must NOT float above the landscape.`

  const preservationSection = safeExistingElements.length > 0
    ? `PRESERVE THESE EXISTING ELEMENTS:
${safeExistingElements.map(el => `- ${el}`).join('\n')}
Do not remove or alter these features. They are part of the world's history.`
    : `This is an early evolution of the world. The base landscape should remain visible.`

  return `WORLD EVOLUTION: Learning about "${safeTopicName}"
${safeSummary ? `\nTOPIC SUMMARY: ${safeSummary}` : ''}

CURRENT TIER: ${tier}
The current world state includes: ${styleDescriptor}

${preservationSection}
${placementGuidance}
${placementHintSection}

ADD TO THE WORLD:
Add exactly ONE new element that directly represents the topic.
Specifically, introduce ${safeElementToAdd} that emerges naturally from the existing landscape.
${skyRestrictions}

STYLE REQUIREMENTS:
- Maintain ${WORLD_STYLE.lighting}
- Continue ${WORLD_STYLE.palette}
- Keep the horizon line consistent with the existing world
- Preserve atmospheric perspective and depth
- The addition should feel organic, as if it grew from the world itself

COMPOSITION GUIDANCE:
- The new ${safeElementToAdd} should integrate with the existing landscape
- Maintain the 16:9 widescreen format
- Keep the same camera angle and horizon position
- Add visual interest without overwhelming existing elements

RESTRICTIONS:
- No text, labels, UI elements, or symbols
- No characters or people
- Do not remove existing elements
- No sudden or jarring changes
- The evolution should feel natural and gradual
- Maintain the dreamlike, ${styleDescriptor} quality throughout
- Do NOT add extra unrelated creatures/plants/objects beyond the ONE new element

This evolution represents knowledge taking root in the world.`
}

export default {
  buildBaseWorldPrompt,
  buildEvolutionPrompt,
  WORLD_STYLE
}
